version: "3.5"
services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run migrate && npm run start:dev"
    build: .
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    networks:
      - libnet
    depends_on: 
      - postgres
    volumes:
      - ./:/app  
    restart: unless-stopped
      
  
  postgres:
    image: postgres:14-alpine
    build: /postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data    
    command: ["postgres", "-c", "logging_collector=true", "-c", "log_statement=all"]
    networks:
      - libnet
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

volumes:
  pgdata:
  logs:

networks:
  libnet:
    driver: bridge