version: "3.5"
services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run migrate && npm run start:dev"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app  
      
  
  postgres:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata:
