version: '3.5'
services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run migrate && npm run start:dev"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app  
      
  
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  pgdata:
